use_frameworks!

target 'AirMapSDK-Example-iOS' do
	platform :ios, '9.0'
	pod 'Alamofire', '~> 4.0'
	pod 'AirMapSDK', :path => '../'
	pod 'Mapbox-iOS-SDK'
	pod 'SwiftTurf', :path => '../../SwiftTurf/'
end

target 'AirMapSDK-Example-macOS' do
	platform :osx, '10.11'
	pod 'AirMapSDK', :path => '../'
end

target 'AirMapSDKTests' do
	platform :ios, '9.0'
	pod 'AirMapSDK', :path => '../'
	pod 'Quick'
	pod 'Nimble'
	pod 'OHHTTPStubs'
	pod 'OHHTTPStubs/Swift'
end
