// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "telemetry.proto"
// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct Airmap { public struct Telemetry { }}

public func == (lhs: Airmap.Telemetry.Position, rhs: Airmap.Telemetry.Position) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasTimestamp == rhs.hasTimestamp) && (!lhs.hasTimestamp || lhs.timestamp == rhs.timestamp)
  fieldCheck = fieldCheck && (lhs.hasLatitude == rhs.hasLatitude) && (!lhs.hasLatitude || lhs.latitude == rhs.latitude)
  fieldCheck = fieldCheck && (lhs.hasLongitude == rhs.hasLongitude) && (!lhs.hasLongitude || lhs.longitude == rhs.longitude)
  fieldCheck = fieldCheck && (lhs.hasAltitudeAgl == rhs.hasAltitudeAgl) && (!lhs.hasAltitudeAgl || lhs.altitudeAgl == rhs.altitudeAgl)
  fieldCheck = fieldCheck && (lhs.hasAltitudeMsl == rhs.hasAltitudeMsl) && (!lhs.hasAltitudeMsl || lhs.altitudeMsl == rhs.altitudeMsl)
  fieldCheck = fieldCheck && (lhs.hasHorizontalAccuracy == rhs.hasHorizontalAccuracy) && (!lhs.hasHorizontalAccuracy || lhs.horizontalAccuracy == rhs.horizontalAccuracy)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public func == (lhs: Airmap.Telemetry.Attitude, rhs: Airmap.Telemetry.Attitude) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasTimestamp == rhs.hasTimestamp) && (!lhs.hasTimestamp || lhs.timestamp == rhs.timestamp)
  fieldCheck = fieldCheck && (lhs.hasYaw == rhs.hasYaw) && (!lhs.hasYaw || lhs.yaw == rhs.yaw)
  fieldCheck = fieldCheck && (lhs.hasPitch == rhs.hasPitch) && (!lhs.hasPitch || lhs.pitch == rhs.pitch)
  fieldCheck = fieldCheck && (lhs.hasRoll == rhs.hasRoll) && (!lhs.hasRoll || lhs.roll == rhs.roll)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public func == (lhs: Airmap.Telemetry.Speed, rhs: Airmap.Telemetry.Speed) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasTimestamp == rhs.hasTimestamp) && (!lhs.hasTimestamp || lhs.timestamp == rhs.timestamp)
  fieldCheck = fieldCheck && (lhs.hasVelocityX == rhs.hasVelocityX) && (!lhs.hasVelocityX || lhs.velocityX == rhs.velocityX)
  fieldCheck = fieldCheck && (lhs.hasVelocityY == rhs.hasVelocityY) && (!lhs.hasVelocityY || lhs.velocityY == rhs.velocityY)
  fieldCheck = fieldCheck && (lhs.hasVelocityZ == rhs.hasVelocityZ) && (!lhs.hasVelocityZ || lhs.velocityZ == rhs.velocityZ)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public func == (lhs: Airmap.Telemetry.Barometer, rhs: Airmap.Telemetry.Barometer) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasTimestamp == rhs.hasTimestamp) && (!lhs.hasTimestamp || lhs.timestamp == rhs.timestamp)
  fieldCheck = fieldCheck && (lhs.hasPressure == rhs.hasPressure) && (!lhs.hasPressure || lhs.pressure == rhs.pressure)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

public extension Airmap.Telemetry {
  public struct TelemetryRoot {
    public static var sharedInstance : TelemetryRoot {
     struct Static {
         static let instance : TelemetryRoot = TelemetryRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final public class Position : GeneratedMessage, GeneratedMessageProtocol {
    // UNIX time in Milliseconds
    public private(set) var hasTimestamp:Bool = false
    public private(set) var timestamp:UInt64 = UInt64(0)

    // The recorded latitude
    // Decimal place requirement: 7 decimal places.
    public private(set) var hasLatitude:Bool = false
    public private(set) var latitude:Double = Double(0)

    // The recorded longitude
    // Decimal place requirement: 7 decimal places.
    public private(set) var hasLongitude:Bool = false
    public private(set) var longitude:Double = Double(0)

    //Altitude above mean sea level (ie. GPS), meters
    public private(set) var hasAltitudeAgl:Bool = false
    public private(set) var altitudeAgl:Float = Float(0)

    // Altitude above ground level, meters
    public private(set) var hasAltitudeMsl:Bool = false
    public private(set) var altitudeMsl:Float = Float(0)

    // Horizontal Dilution of Precision, in meters
    public private(set) var hasHorizontalAccuracy:Bool = false
    public private(set) var horizontalAccuracy:Float = Float(0)

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasTimestamp {
        try output.writeUInt64(1, value:timestamp)
      }
      if hasLatitude {
        try output.writeDouble(2, value:latitude)
      }
      if hasLongitude {
        try output.writeDouble(3, value:longitude)
      }
      if hasAltitudeAgl {
        try output.writeFloat(4, value:altitudeAgl)
      }
      if hasAltitudeMsl {
        try output.writeFloat(5, value:altitudeMsl)
      }
      if hasHorizontalAccuracy {
        try output.writeFloat(6, value:horizontalAccuracy)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasTimestamp {
        serialize_size += timestamp.computeUInt64Size(1)
      }
      if hasLatitude {
        serialize_size += latitude.computeDoubleSize(2)
      }
      if hasLongitude {
        serialize_size += longitude.computeDoubleSize(3)
      }
      if hasAltitudeAgl {
        serialize_size += altitudeAgl.computeFloatSize(4)
      }
      if hasAltitudeMsl {
        serialize_size += altitudeMsl.computeFloatSize(5)
      }
      if hasHorizontalAccuracy {
        serialize_size += horizontalAccuracy.computeFloatSize(6)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Airmap.Telemetry.Position> {
      var mergedArray = Array<Airmap.Telemetry.Position>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Position? {
      return try Airmap.Telemetry.Position.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder().mergeFromData(data, extensionRegistry:Airmap.Telemetry.TelemetryRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Airmap.Telemetry.Position.Builder {
      return Airmap.Telemetry.Position.classBuilder() as! Airmap.Telemetry.Position.Builder
    }
    public func getBuilder() -> Airmap.Telemetry.Position.Builder {
      return classBuilder() as! Airmap.Telemetry.Position.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Position.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Position.Builder()
    }
    public func toBuilder() throws -> Airmap.Telemetry.Position.Builder {
      return try Airmap.Telemetry.Position.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Airmap.Telemetry.Position) throws -> Airmap.Telemetry.Position.Builder {
      return try Airmap.Telemetry.Position.Builder().mergeFrom(prototype)
    }
    public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasTimestamp {
        jsonMap["timestamp"] = "\(timestamp)"
      }
      if hasLatitude {
        jsonMap["latitude"] = NSNumber(double:latitude)
      }
      if hasLongitude {
        jsonMap["longitude"] = NSNumber(double:longitude)
      }
      if hasAltitudeAgl {
        jsonMap["altitudeAgl"] = NSNumber(float:altitudeAgl)
      }
      if hasAltitudeMsl {
        jsonMap["altitudeMsl"] = NSNumber(float:altitudeMsl)
      }
      if hasHorizontalAccuracy {
        jsonMap["horizontalAccuracy"] = NSNumber(float:horizontalAccuracy)
      }
      return jsonMap
    }
    class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder.decodeToBuilder(jsonMap).build()
    }
    class public func fromJSON(data:NSData) throws -> Airmap.Telemetry.Position {
      return try Airmap.Telemetry.Position.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if hasTimestamp {
        output += "\(indent) timestamp: \(timestamp) \n"
      }
      if hasLatitude {
        output += "\(indent) latitude: \(latitude) \n"
      }
      if hasLongitude {
        output += "\(indent) longitude: \(longitude) \n"
      }
      if hasAltitudeAgl {
        output += "\(indent) altitudeAgl: \(altitudeAgl) \n"
      }
      if hasAltitudeMsl {
        output += "\(indent) altitudeMsl: \(altitudeMsl) \n"
      }
      if hasHorizontalAccuracy {
        output += "\(indent) horizontalAccuracy: \(horizontalAccuracy) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasTimestamp {
               hashCode = (hashCode &* 31) &+ timestamp.hashValue
            }
            if hasLatitude {
               hashCode = (hashCode &* 31) &+ latitude.hashValue
            }
            if hasLongitude {
               hashCode = (hashCode &* 31) &+ longitude.hashValue
            }
            if hasAltitudeAgl {
               hashCode = (hashCode &* 31) &+ altitudeAgl.hashValue
            }
            if hasAltitudeMsl {
               hashCode = (hashCode &* 31) &+ altitudeMsl.hashValue
            }
            if hasHorizontalAccuracy {
               hashCode = (hashCode &* 31) &+ horizontalAccuracy.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Airmap.Telemetry.Position"
    }
    override public func className() -> String {
        return "Airmap.Telemetry.Position"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Airmap.Telemetry.Position.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Airmap.Telemetry.Position = Airmap.Telemetry.Position()
      public func getMessage() -> Airmap.Telemetry.Position {
          return builderResult
      }

      required override public init () {
         super.init()
      }
      public var hasTimestamp:Bool {
           get {
                return builderResult.hasTimestamp
           }
      }
      public var timestamp:UInt64 {
           get {
                return builderResult.timestamp
           }
           set (value) {
               builderResult.hasTimestamp = true
               builderResult.timestamp = value
           }
      }
      public func setTimestamp(value:UInt64) -> Airmap.Telemetry.Position.Builder {
        self.timestamp = value
        return self
      }
      public func clearTimestamp() -> Airmap.Telemetry.Position.Builder{
           builderResult.hasTimestamp = false
           builderResult.timestamp = UInt64(0)
           return self
      }
      public var hasLatitude:Bool {
           get {
                return builderResult.hasLatitude
           }
      }
      public var latitude:Double {
           get {
                return builderResult.latitude
           }
           set (value) {
               builderResult.hasLatitude = true
               builderResult.latitude = value
           }
      }
      public func setLatitude(value:Double) -> Airmap.Telemetry.Position.Builder {
        self.latitude = value
        return self
      }
      public func clearLatitude() -> Airmap.Telemetry.Position.Builder{
           builderResult.hasLatitude = false
           builderResult.latitude = Double(0)
           return self
      }
      public var hasLongitude:Bool {
           get {
                return builderResult.hasLongitude
           }
      }
      public var longitude:Double {
           get {
                return builderResult.longitude
           }
           set (value) {
               builderResult.hasLongitude = true
               builderResult.longitude = value
           }
      }
      public func setLongitude(value:Double) -> Airmap.Telemetry.Position.Builder {
        self.longitude = value
        return self
      }
      public func clearLongitude() -> Airmap.Telemetry.Position.Builder{
           builderResult.hasLongitude = false
           builderResult.longitude = Double(0)
           return self
      }
      public var hasAltitudeAgl:Bool {
           get {
                return builderResult.hasAltitudeAgl
           }
      }
      public var altitudeAgl:Float {
           get {
                return builderResult.altitudeAgl
           }
           set (value) {
               builderResult.hasAltitudeAgl = true
               builderResult.altitudeAgl = value
           }
      }
      public func setAltitudeAgl(value:Float) -> Airmap.Telemetry.Position.Builder {
        self.altitudeAgl = value
        return self
      }
      public func clearAltitudeAgl() -> Airmap.Telemetry.Position.Builder{
           builderResult.hasAltitudeAgl = false
           builderResult.altitudeAgl = Float(0)
           return self
      }
      public var hasAltitudeMsl:Bool {
           get {
                return builderResult.hasAltitudeMsl
           }
      }
      public var altitudeMsl:Float {
           get {
                return builderResult.altitudeMsl
           }
           set (value) {
               builderResult.hasAltitudeMsl = true
               builderResult.altitudeMsl = value
           }
      }
      public func setAltitudeMsl(value:Float) -> Airmap.Telemetry.Position.Builder {
        self.altitudeMsl = value
        return self
      }
      public func clearAltitudeMsl() -> Airmap.Telemetry.Position.Builder{
           builderResult.hasAltitudeMsl = false
           builderResult.altitudeMsl = Float(0)
           return self
      }
      public var hasHorizontalAccuracy:Bool {
           get {
                return builderResult.hasHorizontalAccuracy
           }
      }
      public var horizontalAccuracy:Float {
           get {
                return builderResult.horizontalAccuracy
           }
           set (value) {
               builderResult.hasHorizontalAccuracy = true
               builderResult.horizontalAccuracy = value
           }
      }
      public func setHorizontalAccuracy(value:Float) -> Airmap.Telemetry.Position.Builder {
        self.horizontalAccuracy = value
        return self
      }
      public func clearHorizontalAccuracy() -> Airmap.Telemetry.Position.Builder{
           builderResult.hasHorizontalAccuracy = false
           builderResult.horizontalAccuracy = Float(0)
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Airmap.Telemetry.Position.Builder {
        builderResult = Airmap.Telemetry.Position()
        return self
      }
      override public func clone() throws -> Airmap.Telemetry.Position.Builder {
        return try Airmap.Telemetry.Position.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Airmap.Telemetry.Position {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Airmap.Telemetry.Position {
        let returnMe:Airmap.Telemetry.Position = builderResult
        return returnMe
      }
      public func mergeFrom(other:Airmap.Telemetry.Position) throws -> Airmap.Telemetry.Position.Builder {
        if other == Airmap.Telemetry.Position() {
         return self
        }
        if other.hasTimestamp {
             timestamp = other.timestamp
        }
        if other.hasLatitude {
             latitude = other.latitude
        }
        if other.hasLongitude {
             longitude = other.longitude
        }
        if other.hasAltitudeAgl {
             altitudeAgl = other.altitudeAgl
        }
        if other.hasAltitudeMsl {
             altitudeMsl = other.altitudeMsl
        }
        if other.hasHorizontalAccuracy {
             horizontalAccuracy = other.horizontalAccuracy
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Position.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Position.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            timestamp = try input.readUInt64()

          case 17:
            latitude = try input.readDouble()

          case 25:
            longitude = try input.readDouble()

          case 37:
            altitudeAgl = try input.readFloat()

          case 45:
            altitudeMsl = try input.readFloat()

          case 53:
            horizontalAccuracy = try input.readFloat()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Position.Builder {
        let resultDecodedBuilder = Airmap.Telemetry.Position.Builder()
        if let jsonValueTimestamp = jsonMap["timestamp"] as? String {
          resultDecodedBuilder.timestamp = UInt64(jsonValueTimestamp)!
        }
        if let jsonValueLatitude = jsonMap["latitude"] as? NSNumber {
          resultDecodedBuilder.latitude = jsonValueLatitude.doubleValue
        }
        if let jsonValueLongitude = jsonMap["longitude"] as? NSNumber {
          resultDecodedBuilder.longitude = jsonValueLongitude.doubleValue
        }
        if let jsonValueAltitudeAgl = jsonMap["altitudeAgl"] as? NSNumber {
          resultDecodedBuilder.altitudeAgl = jsonValueAltitudeAgl.floatValue
        }
        if let jsonValueAltitudeMsl = jsonMap["altitudeMsl"] as? NSNumber {
          resultDecodedBuilder.altitudeMsl = jsonValueAltitudeMsl.floatValue
        }
        if let jsonValueHorizontalAccuracy = jsonMap["horizontalAccuracy"] as? NSNumber {
          resultDecodedBuilder.horizontalAccuracy = jsonValueHorizontalAccuracy.floatValue
        }
        return resultDecodedBuilder
      }
      class public func fromJSONToBuilder(data:NSData) throws -> Airmap.Telemetry.Position.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Airmap.Telemetry.Position.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

  final public class Attitude : GeneratedMessage, GeneratedMessageProtocol {
    // UNIX time in Milliseconds
    public private(set) var hasTimestamp:Bool = false
    public private(set) var timestamp:UInt64 = UInt64(0)

    // Yaw angle measured from True North, { 0 <= x < 360 } degrees
    public private(set) var hasYaw:Bool = false
    public private(set) var yaw:Float = Float(0)

    // Pitch angle, { -180 < x <= 180 } degrees
    public private(set) var hasPitch:Bool = false
    public private(set) var pitch:Float = Float(0)

    // Roll angle, { -180 < x <= 180 } degrees
    public private(set) var hasRoll:Bool = false
    public private(set) var roll:Float = Float(0)

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasTimestamp {
        try output.writeUInt64(1, value:timestamp)
      }
      if hasYaw {
        try output.writeFloat(2, value:yaw)
      }
      if hasPitch {
        try output.writeFloat(3, value:pitch)
      }
      if hasRoll {
        try output.writeFloat(4, value:roll)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasTimestamp {
        serialize_size += timestamp.computeUInt64Size(1)
      }
      if hasYaw {
        serialize_size += yaw.computeFloatSize(2)
      }
      if hasPitch {
        serialize_size += pitch.computeFloatSize(3)
      }
      if hasRoll {
        serialize_size += roll.computeFloatSize(4)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Airmap.Telemetry.Attitude> {
      var mergedArray = Array<Airmap.Telemetry.Attitude>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Attitude? {
      return try Airmap.Telemetry.Attitude.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder().mergeFromData(data, extensionRegistry:Airmap.Telemetry.TelemetryRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Airmap.Telemetry.Attitude.Builder {
      return Airmap.Telemetry.Attitude.classBuilder() as! Airmap.Telemetry.Attitude.Builder
    }
    public func getBuilder() -> Airmap.Telemetry.Attitude.Builder {
      return classBuilder() as! Airmap.Telemetry.Attitude.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Attitude.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Attitude.Builder()
    }
    public func toBuilder() throws -> Airmap.Telemetry.Attitude.Builder {
      return try Airmap.Telemetry.Attitude.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Airmap.Telemetry.Attitude) throws -> Airmap.Telemetry.Attitude.Builder {
      return try Airmap.Telemetry.Attitude.Builder().mergeFrom(prototype)
    }
    public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasTimestamp {
        jsonMap["timestamp"] = "\(timestamp)"
      }
      if hasYaw {
        jsonMap["yaw"] = NSNumber(float:yaw)
      }
      if hasPitch {
        jsonMap["pitch"] = NSNumber(float:pitch)
      }
      if hasRoll {
        jsonMap["roll"] = NSNumber(float:roll)
      }
      return jsonMap
    }
    class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder.decodeToBuilder(jsonMap).build()
    }
    class public func fromJSON(data:NSData) throws -> Airmap.Telemetry.Attitude {
      return try Airmap.Telemetry.Attitude.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if hasTimestamp {
        output += "\(indent) timestamp: \(timestamp) \n"
      }
      if hasYaw {
        output += "\(indent) yaw: \(yaw) \n"
      }
      if hasPitch {
        output += "\(indent) pitch: \(pitch) \n"
      }
      if hasRoll {
        output += "\(indent) roll: \(roll) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasTimestamp {
               hashCode = (hashCode &* 31) &+ timestamp.hashValue
            }
            if hasYaw {
               hashCode = (hashCode &* 31) &+ yaw.hashValue
            }
            if hasPitch {
               hashCode = (hashCode &* 31) &+ pitch.hashValue
            }
            if hasRoll {
               hashCode = (hashCode &* 31) &+ roll.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Airmap.Telemetry.Attitude"
    }
    override public func className() -> String {
        return "Airmap.Telemetry.Attitude"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Airmap.Telemetry.Attitude.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Airmap.Telemetry.Attitude = Airmap.Telemetry.Attitude()
      public func getMessage() -> Airmap.Telemetry.Attitude {
          return builderResult
      }

      required override public init () {
         super.init()
      }
      public var hasTimestamp:Bool {
           get {
                return builderResult.hasTimestamp
           }
      }
      public var timestamp:UInt64 {
           get {
                return builderResult.timestamp
           }
           set (value) {
               builderResult.hasTimestamp = true
               builderResult.timestamp = value
           }
      }
      public func setTimestamp(value:UInt64) -> Airmap.Telemetry.Attitude.Builder {
        self.timestamp = value
        return self
      }
      public func clearTimestamp() -> Airmap.Telemetry.Attitude.Builder{
           builderResult.hasTimestamp = false
           builderResult.timestamp = UInt64(0)
           return self
      }
      public var hasYaw:Bool {
           get {
                return builderResult.hasYaw
           }
      }
      public var yaw:Float {
           get {
                return builderResult.yaw
           }
           set (value) {
               builderResult.hasYaw = true
               builderResult.yaw = value
           }
      }
      public func setYaw(value:Float) -> Airmap.Telemetry.Attitude.Builder {
        self.yaw = value
        return self
      }
      public func clearYaw() -> Airmap.Telemetry.Attitude.Builder{
           builderResult.hasYaw = false
           builderResult.yaw = Float(0)
           return self
      }
      public var hasPitch:Bool {
           get {
                return builderResult.hasPitch
           }
      }
      public var pitch:Float {
           get {
                return builderResult.pitch
           }
           set (value) {
               builderResult.hasPitch = true
               builderResult.pitch = value
           }
      }
      public func setPitch(value:Float) -> Airmap.Telemetry.Attitude.Builder {
        self.pitch = value
        return self
      }
      public func clearPitch() -> Airmap.Telemetry.Attitude.Builder{
           builderResult.hasPitch = false
           builderResult.pitch = Float(0)
           return self
      }
      public var hasRoll:Bool {
           get {
                return builderResult.hasRoll
           }
      }
      public var roll:Float {
           get {
                return builderResult.roll
           }
           set (value) {
               builderResult.hasRoll = true
               builderResult.roll = value
           }
      }
      public func setRoll(value:Float) -> Airmap.Telemetry.Attitude.Builder {
        self.roll = value
        return self
      }
      public func clearRoll() -> Airmap.Telemetry.Attitude.Builder{
           builderResult.hasRoll = false
           builderResult.roll = Float(0)
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Airmap.Telemetry.Attitude.Builder {
        builderResult = Airmap.Telemetry.Attitude()
        return self
      }
      override public func clone() throws -> Airmap.Telemetry.Attitude.Builder {
        return try Airmap.Telemetry.Attitude.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Airmap.Telemetry.Attitude {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Airmap.Telemetry.Attitude {
        let returnMe:Airmap.Telemetry.Attitude = builderResult
        return returnMe
      }
      public func mergeFrom(other:Airmap.Telemetry.Attitude) throws -> Airmap.Telemetry.Attitude.Builder {
        if other == Airmap.Telemetry.Attitude() {
         return self
        }
        if other.hasTimestamp {
             timestamp = other.timestamp
        }
        if other.hasYaw {
             yaw = other.yaw
        }
        if other.hasPitch {
             pitch = other.pitch
        }
        if other.hasRoll {
             roll = other.roll
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Attitude.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Attitude.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            timestamp = try input.readUInt64()

          case 21:
            yaw = try input.readFloat()

          case 29:
            pitch = try input.readFloat()

          case 37:
            roll = try input.readFloat()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Attitude.Builder {
        let resultDecodedBuilder = Airmap.Telemetry.Attitude.Builder()
        if let jsonValueTimestamp = jsonMap["timestamp"] as? String {
          resultDecodedBuilder.timestamp = UInt64(jsonValueTimestamp)!
        }
        if let jsonValueYaw = jsonMap["yaw"] as? NSNumber {
          resultDecodedBuilder.yaw = jsonValueYaw.floatValue
        }
        if let jsonValuePitch = jsonMap["pitch"] as? NSNumber {
          resultDecodedBuilder.pitch = jsonValuePitch.floatValue
        }
        if let jsonValueRoll = jsonMap["roll"] as? NSNumber {
          resultDecodedBuilder.roll = jsonValueRoll.floatValue
        }
        return resultDecodedBuilder
      }
      class public func fromJSONToBuilder(data:NSData) throws -> Airmap.Telemetry.Attitude.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Airmap.Telemetry.Attitude.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

  final public class Speed : GeneratedMessage, GeneratedMessageProtocol {
    // UNIX time in Milliseconds
    public private(set) var hasTimestamp:Bool = false
    public private(set) var timestamp:UInt64 = UInt64(0)

    // Aircraft Speed in the x direction in meters per second using the North-East-Down (N-E-D) coordinate system
    public private(set) var hasVelocityX:Bool = false
    public private(set) var velocityX:Float = Float(0)

    // Aircraft Speed in the y direction in meters per second using the North-East-Down (N-E-D) coordinate system
    public private(set) var hasVelocityY:Bool = false
    public private(set) var velocityY:Float = Float(0)

    // Aircraft Speed in the z direction in meters per second using the North-East-Down (N-E-D) coordinate system
    public private(set) var hasVelocityZ:Bool = false
    public private(set) var velocityZ:Float = Float(0)

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasTimestamp {
        try output.writeUInt64(1, value:timestamp)
      }
      if hasVelocityX {
        try output.writeFloat(2, value:velocityX)
      }
      if hasVelocityY {
        try output.writeFloat(3, value:velocityY)
      }
      if hasVelocityZ {
        try output.writeFloat(4, value:velocityZ)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasTimestamp {
        serialize_size += timestamp.computeUInt64Size(1)
      }
      if hasVelocityX {
        serialize_size += velocityX.computeFloatSize(2)
      }
      if hasVelocityY {
        serialize_size += velocityY.computeFloatSize(3)
      }
      if hasVelocityZ {
        serialize_size += velocityZ.computeFloatSize(4)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Airmap.Telemetry.Speed> {
      var mergedArray = Array<Airmap.Telemetry.Speed>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Speed? {
      return try Airmap.Telemetry.Speed.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder().mergeFromData(data, extensionRegistry:Airmap.Telemetry.TelemetryRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Airmap.Telemetry.Speed.Builder {
      return Airmap.Telemetry.Speed.classBuilder() as! Airmap.Telemetry.Speed.Builder
    }
    public func getBuilder() -> Airmap.Telemetry.Speed.Builder {
      return classBuilder() as! Airmap.Telemetry.Speed.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Speed.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Speed.Builder()
    }
    public func toBuilder() throws -> Airmap.Telemetry.Speed.Builder {
      return try Airmap.Telemetry.Speed.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Airmap.Telemetry.Speed) throws -> Airmap.Telemetry.Speed.Builder {
      return try Airmap.Telemetry.Speed.Builder().mergeFrom(prototype)
    }
    public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasTimestamp {
        jsonMap["timestamp"] = "\(timestamp)"
      }
      if hasVelocityX {
        jsonMap["velocityX"] = NSNumber(float:velocityX)
      }
      if hasVelocityY {
        jsonMap["velocityY"] = NSNumber(float:velocityY)
      }
      if hasVelocityZ {
        jsonMap["velocityZ"] = NSNumber(float:velocityZ)
      }
      return jsonMap
    }
    class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder.decodeToBuilder(jsonMap).build()
    }
    class public func fromJSON(data:NSData) throws -> Airmap.Telemetry.Speed {
      return try Airmap.Telemetry.Speed.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if hasTimestamp {
        output += "\(indent) timestamp: \(timestamp) \n"
      }
      if hasVelocityX {
        output += "\(indent) velocityX: \(velocityX) \n"
      }
      if hasVelocityY {
        output += "\(indent) velocityY: \(velocityY) \n"
      }
      if hasVelocityZ {
        output += "\(indent) velocityZ: \(velocityZ) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasTimestamp {
               hashCode = (hashCode &* 31) &+ timestamp.hashValue
            }
            if hasVelocityX {
               hashCode = (hashCode &* 31) &+ velocityX.hashValue
            }
            if hasVelocityY {
               hashCode = (hashCode &* 31) &+ velocityY.hashValue
            }
            if hasVelocityZ {
               hashCode = (hashCode &* 31) &+ velocityZ.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Airmap.Telemetry.Speed"
    }
    override public func className() -> String {
        return "Airmap.Telemetry.Speed"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Airmap.Telemetry.Speed.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Airmap.Telemetry.Speed = Airmap.Telemetry.Speed()
      public func getMessage() -> Airmap.Telemetry.Speed {
          return builderResult
      }

      required override public init () {
         super.init()
      }
      public var hasTimestamp:Bool {
           get {
                return builderResult.hasTimestamp
           }
      }
      public var timestamp:UInt64 {
           get {
                return builderResult.timestamp
           }
           set (value) {
               builderResult.hasTimestamp = true
               builderResult.timestamp = value
           }
      }
      public func setTimestamp(value:UInt64) -> Airmap.Telemetry.Speed.Builder {
        self.timestamp = value
        return self
      }
      public func clearTimestamp() -> Airmap.Telemetry.Speed.Builder{
           builderResult.hasTimestamp = false
           builderResult.timestamp = UInt64(0)
           return self
      }
      public var hasVelocityX:Bool {
           get {
                return builderResult.hasVelocityX
           }
      }
      public var velocityX:Float {
           get {
                return builderResult.velocityX
           }
           set (value) {
               builderResult.hasVelocityX = true
               builderResult.velocityX = value
           }
      }
      public func setVelocityX(value:Float) -> Airmap.Telemetry.Speed.Builder {
        self.velocityX = value
        return self
      }
      public func clearVelocityX() -> Airmap.Telemetry.Speed.Builder{
           builderResult.hasVelocityX = false
           builderResult.velocityX = Float(0)
           return self
      }
      public var hasVelocityY:Bool {
           get {
                return builderResult.hasVelocityY
           }
      }
      public var velocityY:Float {
           get {
                return builderResult.velocityY
           }
           set (value) {
               builderResult.hasVelocityY = true
               builderResult.velocityY = value
           }
      }
      public func setVelocityY(value:Float) -> Airmap.Telemetry.Speed.Builder {
        self.velocityY = value
        return self
      }
      public func clearVelocityY() -> Airmap.Telemetry.Speed.Builder{
           builderResult.hasVelocityY = false
           builderResult.velocityY = Float(0)
           return self
      }
      public var hasVelocityZ:Bool {
           get {
                return builderResult.hasVelocityZ
           }
      }
      public var velocityZ:Float {
           get {
                return builderResult.velocityZ
           }
           set (value) {
               builderResult.hasVelocityZ = true
               builderResult.velocityZ = value
           }
      }
      public func setVelocityZ(value:Float) -> Airmap.Telemetry.Speed.Builder {
        self.velocityZ = value
        return self
      }
      public func clearVelocityZ() -> Airmap.Telemetry.Speed.Builder{
           builderResult.hasVelocityZ = false
           builderResult.velocityZ = Float(0)
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Airmap.Telemetry.Speed.Builder {
        builderResult = Airmap.Telemetry.Speed()
        return self
      }
      override public func clone() throws -> Airmap.Telemetry.Speed.Builder {
        return try Airmap.Telemetry.Speed.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Airmap.Telemetry.Speed {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Airmap.Telemetry.Speed {
        let returnMe:Airmap.Telemetry.Speed = builderResult
        return returnMe
      }
      public func mergeFrom(other:Airmap.Telemetry.Speed) throws -> Airmap.Telemetry.Speed.Builder {
        if other == Airmap.Telemetry.Speed() {
         return self
        }
        if other.hasTimestamp {
             timestamp = other.timestamp
        }
        if other.hasVelocityX {
             velocityX = other.velocityX
        }
        if other.hasVelocityY {
             velocityY = other.velocityY
        }
        if other.hasVelocityZ {
             velocityZ = other.velocityZ
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Speed.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            timestamp = try input.readUInt64()

          case 21:
            velocityX = try input.readFloat()

          case 29:
            velocityY = try input.readFloat()

          case 37:
            velocityZ = try input.readFloat()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Speed.Builder {
        let resultDecodedBuilder = Airmap.Telemetry.Speed.Builder()
        if let jsonValueTimestamp = jsonMap["timestamp"] as? String {
          resultDecodedBuilder.timestamp = UInt64(jsonValueTimestamp)!
        }
        if let jsonValueVelocityX = jsonMap["velocityX"] as? NSNumber {
          resultDecodedBuilder.velocityX = jsonValueVelocityX.floatValue
        }
        if let jsonValueVelocityY = jsonMap["velocityY"] as? NSNumber {
          resultDecodedBuilder.velocityY = jsonValueVelocityY.floatValue
        }
        if let jsonValueVelocityZ = jsonMap["velocityZ"] as? NSNumber {
          resultDecodedBuilder.velocityZ = jsonValueVelocityZ.floatValue
        }
        return resultDecodedBuilder
      }
      class public func fromJSONToBuilder(data:NSData) throws -> Airmap.Telemetry.Speed.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Airmap.Telemetry.Speed.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

  final public class Barometer : GeneratedMessage, GeneratedMessageProtocol {
    // UNIX time in Milliseconds
    public private(set) var hasTimestamp:Bool = false
    public private(set) var timestamp:UInt64 = UInt64(0)

    // Barometric pressure in hPa
    public private(set) var hasPressure:Bool = false
    public private(set) var pressure:Float = Float(0)

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasTimestamp {
        try output.writeUInt64(1, value:timestamp)
      }
      if hasPressure {
        try output.writeFloat(2, value:pressure)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasTimestamp {
        serialize_size += timestamp.computeUInt64Size(1)
      }
      if hasPressure {
        serialize_size += pressure.computeFloatSize(2)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Airmap.Telemetry.Barometer> {
      var mergedArray = Array<Airmap.Telemetry.Barometer>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    public class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Barometer? {
      return try Airmap.Telemetry.Barometer.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    public class func parseFromData(data:NSData) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder().mergeFromData(data, extensionRegistry:Airmap.Telemetry.TelemetryRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func getBuilder() -> Airmap.Telemetry.Barometer.Builder {
      return Airmap.Telemetry.Barometer.classBuilder() as! Airmap.Telemetry.Barometer.Builder
    }
    public func getBuilder() -> Airmap.Telemetry.Barometer.Builder {
      return classBuilder() as! Airmap.Telemetry.Barometer.Builder
    }
    override public class func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Barometer.Builder()
    }
    override public func classBuilder() -> MessageBuilder {
      return Airmap.Telemetry.Barometer.Builder()
    }
    public func toBuilder() throws -> Airmap.Telemetry.Barometer.Builder {
      return try Airmap.Telemetry.Barometer.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Airmap.Telemetry.Barometer) throws -> Airmap.Telemetry.Barometer.Builder {
      return try Airmap.Telemetry.Barometer.Builder().mergeFrom(prototype)
    }
    public func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasTimestamp {
        jsonMap["timestamp"] = "\(timestamp)"
      }
      if hasPressure {
        jsonMap["pressure"] = NSNumber(float:pressure)
      }
      return jsonMap
    }
    class public func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder.decodeToBuilder(jsonMap).build()
    }
    class public func fromJSON(data:NSData) throws -> Airmap.Telemetry.Barometer {
      return try Airmap.Telemetry.Barometer.Builder.fromJSONToBuilder(data).build()
    }
    override public func getDescription(indent:String) throws -> String {
      var output = ""
      if hasTimestamp {
        output += "\(indent) timestamp: \(timestamp) \n"
      }
      if hasPressure {
        output += "\(indent) pressure: \(pressure) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasTimestamp {
               hashCode = (hashCode &* 31) &+ timestamp.hashValue
            }
            if hasPressure {
               hashCode = (hashCode &* 31) &+ pressure.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Airmap.Telemetry.Barometer"
    }
    override public func className() -> String {
        return "Airmap.Telemetry.Barometer"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Airmap.Telemetry.Barometer.self
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
      private var builderResult:Airmap.Telemetry.Barometer = Airmap.Telemetry.Barometer()
      public func getMessage() -> Airmap.Telemetry.Barometer {
          return builderResult
      }

      required override public init () {
         super.init()
      }
      public var hasTimestamp:Bool {
           get {
                return builderResult.hasTimestamp
           }
      }
      public var timestamp:UInt64 {
           get {
                return builderResult.timestamp
           }
           set (value) {
               builderResult.hasTimestamp = true
               builderResult.timestamp = value
           }
      }
      public func setTimestamp(value:UInt64) -> Airmap.Telemetry.Barometer.Builder {
        self.timestamp = value
        return self
      }
      public func clearTimestamp() -> Airmap.Telemetry.Barometer.Builder{
           builderResult.hasTimestamp = false
           builderResult.timestamp = UInt64(0)
           return self
      }
      public var hasPressure:Bool {
           get {
                return builderResult.hasPressure
           }
      }
      public var pressure:Float {
           get {
                return builderResult.pressure
           }
           set (value) {
               builderResult.hasPressure = true
               builderResult.pressure = value
           }
      }
      public func setPressure(value:Float) -> Airmap.Telemetry.Barometer.Builder {
        self.pressure = value
        return self
      }
      public func clearPressure() -> Airmap.Telemetry.Barometer.Builder{
           builderResult.hasPressure = false
           builderResult.pressure = Float(0)
           return self
      }
      override public var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override public func clear() -> Airmap.Telemetry.Barometer.Builder {
        builderResult = Airmap.Telemetry.Barometer()
        return self
      }
      override public func clone() throws -> Airmap.Telemetry.Barometer.Builder {
        return try Airmap.Telemetry.Barometer.builderWithPrototype(builderResult)
      }
      override public func build() throws -> Airmap.Telemetry.Barometer {
           try checkInitialized()
           return buildPartial()
      }
      public func buildPartial() -> Airmap.Telemetry.Barometer {
        let returnMe:Airmap.Telemetry.Barometer = builderResult
        return returnMe
      }
      public func mergeFrom(other:Airmap.Telemetry.Barometer) throws -> Airmap.Telemetry.Barometer.Builder {
        if other == Airmap.Telemetry.Barometer() {
         return self
        }
        if other.hasTimestamp {
             timestamp = other.timestamp
        }
        if other.hasPressure {
             pressure = other.pressure
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream) throws -> Airmap.Telemetry.Barometer.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override public func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Barometer.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let protobufTag = try input.readTag()
          switch protobufTag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 8:
            timestamp = try input.readUInt64()

          case 21:
            pressure = try input.readFloat()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      class public func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Airmap.Telemetry.Barometer.Builder {
        let resultDecodedBuilder = Airmap.Telemetry.Barometer.Builder()
        if let jsonValueTimestamp = jsonMap["timestamp"] as? String {
          resultDecodedBuilder.timestamp = UInt64(jsonValueTimestamp)!
        }
        if let jsonValuePressure = jsonMap["pressure"] as? NSNumber {
          resultDecodedBuilder.pressure = jsonValuePressure.floatValue
        }
        return resultDecodedBuilder
      }
      class public func fromJSONToBuilder(data:NSData) throws -> Airmap.Telemetry.Barometer.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Airmap.Telemetry.Barometer.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
