/// Generated by the Protocol Buffers 3.5.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 4.0.0
/// Source file "speed.proto"
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers

public extension Airmap.Telemetry {
    public struct SpeedRoot {
        public static let `default` = SpeedRoot()
        public var extensionRegistry:ExtensionRegistry

        init() {
            extensionRegistry = ExtensionRegistry()
            registerAllExtensions(registry: extensionRegistry)
        }
        public func registerAllExtensions(registry: ExtensionRegistry) {
        }
    }

    final public class Speed : GeneratedMessage {
        public typealias BuilderType = Airmap.Telemetry.Speed.Builder

        public static func == (lhs: Airmap.Telemetry.Speed, rhs: Airmap.Telemetry.Speed) -> Bool {
            if lhs === rhs {
                return true
            }
            var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
            fieldCheck = fieldCheck && (lhs.hasTimestamp == rhs.hasTimestamp) && (!lhs.hasTimestamp || lhs.timestamp == rhs.timestamp)
            fieldCheck = fieldCheck && (lhs.hasVelocityX == rhs.hasVelocityX) && (!lhs.hasVelocityX || lhs.velocityX == rhs.velocityX)
            fieldCheck = fieldCheck && (lhs.hasVelocityY == rhs.hasVelocityY) && (!lhs.hasVelocityY || lhs.velocityY == rhs.velocityY)
            fieldCheck = fieldCheck && (lhs.hasVelocityZ == rhs.hasVelocityZ) && (!lhs.hasVelocityZ || lhs.velocityZ == rhs.velocityZ)
            fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
            return fieldCheck
        }

        /// UNIX time in Milliseconds
        public fileprivate(set) var timestamp:UInt64! = nil
        public fileprivate(set) var hasTimestamp:Bool = false

        /// Aircraft Speed in the x direction in meters per second using the North-East-Down (N-E-D) coordinate system
        public fileprivate(set) var velocityX:Float! = nil
        public fileprivate(set) var hasVelocityX:Bool = false

        /// Aircraft Speed in the y direction in meters per second using the North-East-Down (N-E-D) coordinate system
        public fileprivate(set) var velocityY:Float! = nil
        public fileprivate(set) var hasVelocityY:Bool = false

        /// Aircraft Speed in the z direction in meters per second using the North-East-Down (N-E-D) coordinate system
        public fileprivate(set) var velocityZ:Float! = nil
        public fileprivate(set) var hasVelocityZ:Bool = false

        required public init() {
            super.init()
        }
        override public func isInitialized() throws {
        }
        override public func writeTo(codedOutputStream: CodedOutputStream) throws {
            if hasTimestamp {
                try codedOutputStream.writeUInt64(fieldNumber: 1, value:timestamp)
            }
            if hasVelocityX {
                try codedOutputStream.writeFloat(fieldNumber: 2, value:velocityX)
            }
            if hasVelocityY {
                try codedOutputStream.writeFloat(fieldNumber: 3, value:velocityY)
            }
            if hasVelocityZ {
                try codedOutputStream.writeFloat(fieldNumber: 4, value:velocityZ)
            }
            try unknownFields.writeTo(codedOutputStream: codedOutputStream)
        }
        override public func serializedSize() -> Int32 {
            var serialize_size:Int32 = memoizedSerializedSize
            if serialize_size != -1 {
             return serialize_size
            }

            serialize_size = 0
            if hasTimestamp {
                serialize_size += timestamp.computeUInt64Size(fieldNumber: 1)
            }
            if hasVelocityX {
                serialize_size += velocityX.computeFloatSize(fieldNumber: 2)
            }
            if hasVelocityY {
                serialize_size += velocityY.computeFloatSize(fieldNumber: 3)
            }
            if hasVelocityZ {
                serialize_size += velocityZ.computeFloatSize(fieldNumber: 4)
            }
            serialize_size += unknownFields.serializedSize()
            memoizedSerializedSize = serialize_size
            return serialize_size
        }
        public class func getBuilder() -> Airmap.Telemetry.Speed.Builder {
            return Airmap.Telemetry.Speed.classBuilder() as! Airmap.Telemetry.Speed.Builder
        }
        public func getBuilder() -> Airmap.Telemetry.Speed.Builder {
            return classBuilder() as! Airmap.Telemetry.Speed.Builder
        }
        override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
            return Airmap.Telemetry.Speed.Builder()
        }
        override public func classBuilder() -> ProtocolBuffersMessageBuilder {
            return Airmap.Telemetry.Speed.Builder()
        }
        public func toBuilder() throws -> Airmap.Telemetry.Speed.Builder {
            return try Airmap.Telemetry.Speed.builderWithPrototype(prototype:self)
        }
        public class func builderWithPrototype(prototype:Airmap.Telemetry.Speed) throws -> Airmap.Telemetry.Speed.Builder {
            return try Airmap.Telemetry.Speed.Builder().mergeFrom(other:prototype)
        }
        override public func encode() throws -> Dictionary<String,Any> {
            try isInitialized()
            var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
            if hasTimestamp {
                jsonMap["timestamp"] = "\(timestamp!)"
            }
            if hasVelocityX {
                jsonMap["velocityX"] = Float(velocityX)
            }
            if hasVelocityY {
                jsonMap["velocityY"] = Float(velocityY)
            }
            if hasVelocityZ {
                jsonMap["velocityZ"] = Float(velocityZ)
            }
            return jsonMap
        }
        override class public func decode(jsonMap:Dictionary<String,Any>) throws -> Airmap.Telemetry.Speed {
            return try Airmap.Telemetry.Speed.Builder.decodeToBuilder(jsonMap:jsonMap).build()
        }
        override class public func fromJSON(data:Data) throws -> Airmap.Telemetry.Speed {
            return try Airmap.Telemetry.Speed.Builder.fromJSONToBuilder(data:data).build()
        }
        override public func getDescription(indent:String) throws -> String {
            var output = ""
            if hasTimestamp {
                output += "\(indent) timestamp: \(timestamp) \n"
            }
            if hasVelocityX {
                output += "\(indent) velocityX: \(velocityX) \n"
            }
            if hasVelocityY {
                output += "\(indent) velocityY: \(velocityY) \n"
            }
            if hasVelocityZ {
                output += "\(indent) velocityZ: \(velocityZ) \n"
            }
            output += unknownFields.getDescription(indent: indent)
            return output
        }
        override public var hashValue:Int {
            get {
                var hashCode:Int = 7
                if hasTimestamp {
                    hashCode = (hashCode &* 31) &+ timestamp.hashValue
                }
                if hasVelocityX {
                    hashCode = (hashCode &* 31) &+ velocityX.hashValue
                }
                if hasVelocityY {
                    hashCode = (hashCode &* 31) &+ velocityY.hashValue
                }
                if hasVelocityZ {
                    hashCode = (hashCode &* 31) &+ velocityZ.hashValue
                }
                hashCode = (hashCode &* 31) &+  unknownFields.hashValue
                return hashCode
            }
        }


        //Meta information declaration start

        override public class func className() -> String {
            return "Airmap.Telemetry.Speed"
        }
        override public func className() -> String {
            return "Airmap.Telemetry.Speed"
        }
        //Meta information declaration end

        final public class Builder : GeneratedMessageBuilder {
            fileprivate var builderResult:Airmap.Telemetry.Speed = Airmap.Telemetry.Speed()
            public func getMessage() -> Airmap.Telemetry.Speed {
                return builderResult
            }

            required override public init () {
                super.init()
            }
            /// UNIX time in Milliseconds
            public var timestamp:UInt64 {
                get {
                    return builderResult.timestamp
                }
                set (value) {
                    builderResult.hasTimestamp = true
                    builderResult.timestamp = value
                }
            }
            public var hasTimestamp:Bool {
                get {
                    return builderResult.hasTimestamp
                }
            }
            @discardableResult
            public func setTimestamp(_ value:UInt64) -> Airmap.Telemetry.Speed.Builder {
                self.timestamp = value
                return self
            }
            @discardableResult
            public func clearTimestamp() -> Airmap.Telemetry.Speed.Builder{
                builderResult.hasTimestamp = false
                builderResult.timestamp = nil
                return self
            }
            /// Aircraft Speed in the x direction in meters per second using the North-East-Down (N-E-D) coordinate system
            public var velocityX:Float {
                get {
                    return builderResult.velocityX
                }
                set (value) {
                    builderResult.hasVelocityX = true
                    builderResult.velocityX = value
                }
            }
            public var hasVelocityX:Bool {
                get {
                    return builderResult.hasVelocityX
                }
            }
            @discardableResult
            public func setVelocityX(_ value:Float) -> Airmap.Telemetry.Speed.Builder {
                self.velocityX = value
                return self
            }
            @discardableResult
            public func clearVelocityX() -> Airmap.Telemetry.Speed.Builder{
                builderResult.hasVelocityX = false
                builderResult.velocityX = nil
                return self
            }
            /// Aircraft Speed in the y direction in meters per second using the North-East-Down (N-E-D) coordinate system
            public var velocityY:Float {
                get {
                    return builderResult.velocityY
                }
                set (value) {
                    builderResult.hasVelocityY = true
                    builderResult.velocityY = value
                }
            }
            public var hasVelocityY:Bool {
                get {
                    return builderResult.hasVelocityY
                }
            }
            @discardableResult
            public func setVelocityY(_ value:Float) -> Airmap.Telemetry.Speed.Builder {
                self.velocityY = value
                return self
            }
            @discardableResult
            public func clearVelocityY() -> Airmap.Telemetry.Speed.Builder{
                builderResult.hasVelocityY = false
                builderResult.velocityY = nil
                return self
            }
            /// Aircraft Speed in the z direction in meters per second using the North-East-Down (N-E-D) coordinate system
            public var velocityZ:Float {
                get {
                    return builderResult.velocityZ
                }
                set (value) {
                    builderResult.hasVelocityZ = true
                    builderResult.velocityZ = value
                }
            }
            public var hasVelocityZ:Bool {
                get {
                    return builderResult.hasVelocityZ
                }
            }
            @discardableResult
            public func setVelocityZ(_ value:Float) -> Airmap.Telemetry.Speed.Builder {
                self.velocityZ = value
                return self
            }
            @discardableResult
            public func clearVelocityZ() -> Airmap.Telemetry.Speed.Builder{
                builderResult.hasVelocityZ = false
                builderResult.velocityZ = nil
                return self
            }
            override public var internalGetResult:GeneratedMessage {
                get {
                    return builderResult
                }
            }
            @discardableResult
            override public func clear() -> Airmap.Telemetry.Speed.Builder {
                builderResult = Airmap.Telemetry.Speed()
                return self
            }
            override public func clone() throws -> Airmap.Telemetry.Speed.Builder {
                return try Airmap.Telemetry.Speed.builderWithPrototype(prototype:builderResult)
            }
            override public func build() throws -> Airmap.Telemetry.Speed {
                try checkInitialized()
                return buildPartial()
            }
            public func buildPartial() -> Airmap.Telemetry.Speed {
                let returnMe:Airmap.Telemetry.Speed = builderResult
                return returnMe
            }
            @discardableResult
            public func mergeFrom(other:Airmap.Telemetry.Speed) throws -> Airmap.Telemetry.Speed.Builder {
                if other == Airmap.Telemetry.Speed() {
                    return self
                }
                if other.hasTimestamp {
                    timestamp = other.timestamp
                }
                if other.hasVelocityX {
                    velocityX = other.velocityX
                }
                if other.hasVelocityY {
                    velocityY = other.velocityY
                }
                if other.hasVelocityZ {
                    velocityZ = other.velocityZ
                }
                try merge(unknownField: other.unknownFields)
                return self
            }
            @discardableResult
            override public func mergeFrom(codedInputStream: CodedInputStream) throws -> Airmap.Telemetry.Speed.Builder {
                return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
            }
            @discardableResult
            override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed.Builder {
                let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
                while (true) {
                    let protobufTag = try codedInputStream.readTag()
                    switch protobufTag {
                    case 0: 
                        self.unknownFields = try unknownFieldsBuilder.build()
                        return self

                    case 8:
                        timestamp = try codedInputStream.readUInt64()

                    case 21:
                        velocityX = try codedInputStream.readFloat()

                    case 29:
                        velocityY = try codedInputStream.readFloat()

                    case 37:
                        velocityZ = try codedInputStream.readFloat()

                    default:
                        if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                            unknownFields = try unknownFieldsBuilder.build()
                            return self
                        }
                    }
                }
            }
            class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> Airmap.Telemetry.Speed.Builder {
                let resultDecodedBuilder = Airmap.Telemetry.Speed.Builder()
                if let jsonValueTimestamp = jsonMap["timestamp"] as? String {
                    resultDecodedBuilder.timestamp = UInt64(jsonValueTimestamp)!
                } else if let jsonValueTimestamp = jsonMap["timestamp"] as? UInt {
                    resultDecodedBuilder.timestamp = UInt64(jsonValueTimestamp)
                }
                if let jsonValueVelocityX = jsonMap["velocityX"] as? Float {
                    resultDecodedBuilder.velocityX = Float(jsonValueVelocityX)
                } else if let jsonValueVelocityX = jsonMap["velocityX"] as? String {
                    resultDecodedBuilder.velocityX = Float(jsonValueVelocityX)!
                }
                if let jsonValueVelocityY = jsonMap["velocityY"] as? Float {
                    resultDecodedBuilder.velocityY = Float(jsonValueVelocityY)
                } else if let jsonValueVelocityY = jsonMap["velocityY"] as? String {
                    resultDecodedBuilder.velocityY = Float(jsonValueVelocityY)!
                }
                if let jsonValueVelocityZ = jsonMap["velocityZ"] as? Float {
                    resultDecodedBuilder.velocityZ = Float(jsonValueVelocityZ)
                } else if let jsonValueVelocityZ = jsonMap["velocityZ"] as? String {
                    resultDecodedBuilder.velocityZ = Float(jsonValueVelocityZ)!
                }
                return resultDecodedBuilder
            }
            override class public func fromJSONToBuilder(data:Data) throws -> Airmap.Telemetry.Speed.Builder {
                let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
                guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
                  throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
                }
                return try Airmap.Telemetry.Speed.Builder.decodeToBuilder(jsonMap:jsDataCast)
            }
        }

    }

}
extension Airmap.Telemetry.Speed: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<Airmap.Telemetry.Speed> {
        var mergedArray = Array<Airmap.Telemetry.Speed>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> Airmap.Telemetry.Speed? {
        return try Airmap.Telemetry.Speed.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> Airmap.Telemetry.Speed {
        return try Airmap.Telemetry.Speed.Builder().mergeFrom(data: data, extensionRegistry:Airmap.Telemetry.SpeedRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed {
        return try Airmap.Telemetry.Speed.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> Airmap.Telemetry.Speed {
        return try Airmap.Telemetry.Speed.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed {
        return try Airmap.Telemetry.Speed.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> Airmap.Telemetry.Speed {
        return try Airmap.Telemetry.Speed.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Airmap.Telemetry.Speed {
        return try Airmap.Telemetry.Speed.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "timestamp": return self.timestamp
        case "velocityX": return self.velocityX
        case "velocityY": return self.velocityY
        case "velocityZ": return self.velocityZ
        default: return nil
        }
    }
}
extension Airmap.Telemetry.Speed.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = Airmap.Telemetry.Speed
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "timestamp": return self.timestamp
            case "velocityX": return self.velocityX
            case "velocityY": return self.velocityY
            case "velocityZ": return self.velocityZ
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "timestamp":
                guard let newSubscriptValue = newSubscriptValue as? UInt64 else {
                    return
                }
                self.timestamp = newSubscriptValue
            case "velocityX":
                guard let newSubscriptValue = newSubscriptValue as? Float else {
                    return
                }
                self.velocityX = newSubscriptValue
            case "velocityY":
                guard let newSubscriptValue = newSubscriptValue as? Float else {
                    return
                }
                self.velocityY = newSubscriptValue
            case "velocityZ":
                guard let newSubscriptValue = newSubscriptValue as? Float else {
                    return
                }
                self.velocityZ = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
