//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: remoteid/remoteid.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Remoteid_RemoteIDClient, then call methods of this protocol to make API calls.
internal protocol Remoteid_RemoteIDClientProtocol {
  func monitorArea(_ request: Remoteid_MonitorAreaParameters, callOptions: CallOptions?, handler: @escaping (Remoteid_MonitorAreaResponse) -> Void) -> ServerStreamingCall<Remoteid_MonitorAreaParameters, Remoteid_MonitorAreaResponse>
}

internal final class Remoteid_RemoteIDClient: GRPCClient, Remoteid_RemoteIDClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the remoteid.RemoteID service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// ALPHA: API subject to change
  /// MonitorArea monitors a given area for active operations.
  ///
  /// - Parameters:
  ///   - request: Request to send to MonitorArea.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func monitorArea(_ request: Remoteid_MonitorAreaParameters, callOptions: CallOptions? = nil, handler: @escaping (Remoteid_MonitorAreaResponse) -> Void) -> ServerStreamingCall<Remoteid_MonitorAreaParameters, Remoteid_MonitorAreaResponse> {
    return self.makeServerStreamingCall(path: "/remoteid.RemoteID/MonitorArea",
                                        request: request,
                                        callOptions: callOptions ?? self.defaultCallOptions,
                                        handler: handler)
  }

}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Remoteid_RemoteIDProvider: CallHandlerProvider {
  /// ALPHA: API subject to change
  /// MonitorArea monitors a given area for active operations.
  func monitorArea(request: Remoteid_MonitorAreaParameters, context: StreamingResponseCallContext<Remoteid_MonitorAreaResponse>) -> EventLoopFuture<GRPCStatus>
}

extension Remoteid_RemoteIDProvider {
  internal var serviceName: String { return "remoteid.RemoteID" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "MonitorArea":
      return ServerStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.monitorArea(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload` for request and response messages
extension Remoteid_MonitorAreaParameters: GRPCProtobufPayload {}
extension Remoteid_MonitorAreaResponse: GRPCProtobufPayload {}

